server:
  port: 8084

spring:
  application:
    name: CONFIG-SERVER

  # config server configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MOHAMED-EL-HADDIOUI/microservice-config
          clone-on-start: true
